# coding: utf-8
from sqlalchemy import BigInteger, Boolean, Column, Date, DateTime, Float, Integer, MetaData, Numeric, SmallInteger, String, Table, Text

metadata_or = MetaData()

t_cmbd = Table(
    'cmbd', metadata_or,
    Column('id', BigInteger),
    Column('hospital', Text),
    Column('des_hospital', Text),
    Column('fecha_ingreso', DateTime),
    Column('tipo_ingreso', Text),
    Column('fecha_alta', DateTime),
    Column('servicio_alta', Text),
    Column('serv_alt_desc', Text),
    Column('tipo_alta', Text),
    Column('desc_tipo_alta', Text),
    Column('d1', Text),
    Column('d2', Text),
    Column('d3', Text),
    Column('d4', Text),
    Column('d5', Text),
    Column('d6', Text),
    Column('d7', Text),
    Column('d8', Text),
    Column('d9', Text),
    Column('d10', Text),
    Column('d11', Text),
    Column('d12', Text),
    Column('d13', Text),
    Column('d14', Text),
    Column('d15', Text),
    Column('poa_01', Text),
    Column('poa_02', Text),
    Column('poa_03', Text),
    Column('poa_04', Text),
    Column('poa_05', Text),
    Column('poa_06', Text),
    Column('poa_07', Text),
    Column('poa_08', Text),
    Column('poa_09', Text),
    Column('poa_10', Text),
    Column('poa_11', Text),
    Column('poa_12', Text),
    Column('poa_13', Text),
    Column('poa_14', Text),
    Column('poa_15', Text),
    Column('p1', Text),
    Column('p2', Text),
    Column('p3', Text),
    Column('p4', Text),
    Column('p5', Text),
    Column('p6', Text),
    Column('p7', Text),
    Column('p8', Text),
    Column('p9', Text),
    Column('p10', Text),
    Column('p11', Text),
    Column('p12', Text),
    Column('p13', Text),
    Column('p14', Text),
    Column('p15', Text),
    Column('fecha_intervencion', DateTime),
    Column('reingreso', Text),
    Column('exitus', Text),
    Column('cod_grd', Text),
    Column('des_grd', Text),
    Column('peso', Float(53)),
    Column('severidad', Text),
    Column('mortalidad', Text),
    Column('regcon', SmallInteger),
    Column('reg_finan', SmallInteger),
    Column('desc_reg_finan', Text),
    Column('dias_estancia_real', Integer),
    Column('dias_en_uci', Integer),
    Column('dias_reingreso', Integer),
    schema='origen'
)

t_diag_ap = Table(
    'diag_ap', metadata_or,
    Column('id', BigInteger),
    Column('episodio', Text),
    Column('diag_cd', Text),
    Column('diag_st', Text),
    Column('diag_dt', Date),
    Column('discharge_dt', Date),
    schema='origen'
)

t_laboratory_cdm = Table(
    'laboratory_cdm', metadata_or,
    Column('event_yr', Integer, nullable=False),
    Column('event_mth', Integer, nullable=False),
    Column('obs_id', String),
    Column('coding_cd', String),
    Column('obs_codevalue_st', String),
    Column('obs_method_id', Integer, nullable=False),
    Column('obs_reception_dt', DateTime),
    Column('obs_result_dt', DateTime),
    Column('obs_src_value_nm', Numeric, nullable=False),
    Column('obs_value_nm', Numeric, nullable=False),
    Column('person_id', String),
    Column('placer_clinunit_cd', String),
    Column('placer_clinunit_st', String),
    Column('placer_facility_cd', String),
    Column('req_complete_dt', DateTime),
    Column('req_final_dt', DateTime),
    Column('req_id', String),
    Column('req_last_change_dt', DateTime),
    Column('req_status_cd', String),
    Column('request_dt', DateTime),
    Column('source_cd', String),
    Column('src_observable_cd', String),
    Column('src_observable_st', String),
    Column('src_placer_id', String),
    Column('std_observable_cd', String),
    Column('std_observable_st', String),
    Column('unit_st', String),
    schema='origen'
)

t_phar_presc = Table(
    'phar_presc', metadata_or,
    Column('id', BigInteger),
    Column('año', Integer),
    Column('mes', Integer),
    Column('fecha_prescripcion', Date),
    Column('id_presc', Text),
    Column('codigo_origen', Text),
    Column('nivel_asistencial', Text, nullable=False),
    Column('codigo_nacional_medicamento', Text),
    Column('fecha_inicio_tratamiento', Date),
    Column('fecha_prevista_fin_tratamiento', Date),
    Column('cod_tipo_prescripcion', Integer),
    Column('tipo_prescripcion', Text),
    Column('codigo_atc', Text),
    Column('cod_forma_farma', Text),
    Column('forma_farmaceutica', Text),
    Column('envases_prescritos', Integer),
    Column('numero_ddds', Numeric(38, 6)),
    Column('contenido', Numeric(19, 2)),
    Column('dosis', Numeric(38, 18)),
    Column('unidad_dosis', Text),
    Column('intervalo_admon_tomas', Integer),
    Column('unidad_tiempo', Text, nullable=False),
    Column('cantidad_por_toma', Integer),
    Column('diagnostico', Text),
    Column('diag_obs_st', Text),
    Column('diag_st', Text),
    Column('id_episode', Text),
    Column('codigo_centro', Text),
    Column('cias_prescriptor', Text),
    Column('cod_via_administracion', Text),
    Column('descrip_via', Text),
    Column('id_presc_item', Text),
    Column('id_hoja_prescripcion', Text),
    schema='origen'
)

t_radiology = Table(
    'radiology', metadata_or,
    Column('id', BigInteger),
    Column('año', Integer),
    Column('mes', Integer),
    Column('fecha_prueba', DateTime),
    Column('identificador_rad', Text),
    Column('area', Text),
    Column('episodio', Text),
    Column('codigo_centro', Text),
    Column('codigo_imagen', Text),
    Column('peticionario', Text),
    Column('prestador', Text),
    Column('url', Text),
    schema='origen'
)

t_visits_er = Table(
    'visits_er', metadata_or,
    Column('id', BigInteger),
    Column('origen_ingreso', Text),
    Column('causa_clinica_admision', Text),
    Column('tipo_admision_snomed', Text),
    Column('fecha_atencion_urgencias', DateTime),
    Column('cod_hospital', Text),
    Column('hospital', Text),
    Column('nivel_triaje', Integer),
    Column('cod_destino_alta_snomed', Text),
    Column('centro_destino_alta', Text),
    Column('destino_alta', Text),
    Column('diag1_cie_cd', Text),
    Column('diag2_cie_cd', Text),
    Column('diag3_cie_cd', Text),
    Column('diag1_snomed_cd', Text),
    Column('diag2_snomed_cd', Text),
    Column('diag3_snomed_cd', Text),
    Column('clinic_st', Text),
    Column('diabetes_bl', Integer),
    Column('dyslipidemia_bl', Integer),
    Column('hbp_bl', Integer),
    Column('stroke_bl', Integer),
    Column('fecha_asignacion_cama', DateTime),
    Column('inicio_fibrinolisis', DateTime),
    Column('primera_asistencia', DateTime),
    Column('alta_urgencias', DateTime),
    Column('salida_urgencias', DateTime),
    Column('solicitud_alta', DateTime),
    Column('periodo_ingreso_triaje', Integer),
    schema='origen'
)

t_visits_pc = Table(
    'visits_pc', metadata_or,
    Column('id', BigInteger),
    Column('cod_especialidad', Text),
    Column('especialidad', Text),
    Column('año_visita', Integer),
    Column('fecha_visita', Date),
    Column('cod_tipo_consulta', Text),
    Column('tipo_consulta', Text),
    Column('attentiontype_cd', Text),
    Column('attending_cias_cd', Text),
    schema='origen'
)


t_visits_sc = Table(
    'visits_sc', metadata_or,
    Column('id', BigInteger),
    Column('cod_centro', Text),
    Column('desc_centro', Text),
    Column('cod_hospital', Text),
    Column('hospital', Text),
    Column('fecha_visita', Date),
    Column('realizada', Text),
    Column('unidad_solicitante', Text),
    Column('solicitante', Text),
    Column('cod_prestacion', Text),
    Column('prestacion', Text),
    Column('prestador_servicio', Text),
    Column('prestador', Text),
    Column('cod_derivacion', Integer),
    Column('procedencia', Text),
    Column('radiologia', Boolean),
    schema='origen'
)